name: Checkov Workflow
on:
  push:
    branches:
      - main

env:
  CHECKOV_RESULT_PATH: checkov-results

jobs:
  checkov:
    name: Run Checkov
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
     
    - name: Install Python and Checkov
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --upgrade pip
        pip3 install -U checkov
        checkov --version
        mkdir $CHECKOV_RESULT_PATH            

    - name: Run Checkov
      run: |
        checkov -d . -s --quiet --framework terraform -o cli -o junitxml --output-file-path $CHECKOV_RESULT_PATH

    - name: checkov-results  
      uses: actions/upload-artifact@v2
      with:
        name: checkov-results
        path: ${{ env.CHECKOV_RESULT_PATH }}
        retention-days: 30
        




  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
      
    steps:
    - name: Clone repo
      uses: actions/checkout@master
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        soft_fail: true



# name: tfsec workflow
# on:
#   push:
#     branches:
#       - main

# jobs:
#   checkov:
#     name: Run tfsec
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repo
#       uses: actions/checkout@v2
     
#     - name: Install Python and tfsec
#       run: |
#         curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

#     - name: Run tfsec
#       run: |
#         tfsec . -s